# Generated by Django 5.0.7 on 2024-11-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_documento_asunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='emitido_por_jefe',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rolesusuario',
            name='area',
            field=models.CharField(choices=[('SISTEMAS', 'Sistemas'), ('MARKETING', 'Marketing'), ('VENTAS', 'Ventas'), ('IMAGEN_INSTITUCIONAL', 'Imagen Institucional'), ('ACADEMICA', 'Académica'), ('TESORERIA', 'Tesorería'), ('ALMACEN', 'Almacén'), ('COORDINACION_GENERAL_FOCUS', 'Coordinación General Focus'), ('MARKETING_FOCUS', 'Área Marketing Focus'), ('PRACTICANTE', 'Practicante'), ('GERENCIA', 'Gerencia')], default='SISTEMAS', max_length=50),
        ),
    ]
