# Generated by Django 5.0.7 on 2024-11-19 11:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_documento_emitido_por_jefe_alter_rolesusuario_area'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('archivo_pdf', models.FileField(upload_to='memos/')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('destinatario_tipo', models.CharField(choices=[('todos', 'Todos los jefes de área'), ('jefe_especifico', 'Jefe específico')], max_length=20)),
                ('area_destino', models.CharField(blank=True, choices=[('SISTEMAS', 'Sistemas'), ('MARKETING', 'Marketing'), ('VENTAS', 'Ventas'), ('IMAGEN_INSTITUCIONAL', 'Imagen Institucional'), ('ACADEMICA', 'Académica'), ('TESORERIA', 'Tesorería'), ('ALMACEN', 'Almacén'), ('COORDINACION_GENERAL_FOCUS', 'Coordinación General Focus'), ('MARKETING_FOCUS', 'Área Marketing Focus'), ('PRACTICANTE', 'Practicante'), ('GERENCIA', 'Gerencia')], max_length=50, null=True)),
                ('leido_por', models.ManyToManyField(blank=True, related_name='memos_leidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
