# Generated by Django 5.0.7 on 2024-12-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='rendicion',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
