# Generated by Django 5.0.7 on 2025-01-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_documento_rendicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memo',
            name='area_destino',
            field=models.CharField(blank=True, choices=[('SISTEMAS', 'Sistemas'), ('MARKETING', 'Marketing'), ('VENTAS', 'Ventas'), ('IMAGEN_INSTITUCIONAL', 'Imagen Institucional'), ('ACADEMICA', 'Académica'), ('TESORERIA', 'Tesorería'), ('ALMACEN', 'Almacén'), ('COORDINACION_GENERAL_FOCUS', 'Coordinación General Focus'), ('MARKETING_FOCUS', 'Área Marketing Focus'), ('PRACTICANTE', 'Practicante'), ('GERENCIA', 'Gerencia'), ('OPERATIVA', 'Operativa')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rolesusuario',
            name='area',
            field=models.CharField(choices=[('SISTEMAS', 'Sistemas'), ('MARKETING', 'Marketing'), ('VENTAS', 'Ventas'), ('IMAGEN_INSTITUCIONAL', 'Imagen Institucional'), ('ACADEMICA', 'Académica'), ('TESORERIA', 'Tesorería'), ('ALMACEN', 'Almacén'), ('COORDINACION_GENERAL_FOCUS', 'Coordinación General Focus'), ('MARKETING_FOCUS', 'Área Marketing Focus'), ('PRACTICANTE', 'Practicante'), ('GERENCIA', 'Gerencia'), ('OPERATIVA', 'Operativa')], default='SISTEMAS', max_length=50),
        ),
    ]
