# Generated by Django 5.0.7 on 2025-03-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_documento_fecha_aprobacion_alter_memo_area_destino_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='formatos/', verbose_name='Archivo de Formato')),
            ],
        ),
    ]
