# Generated by Django 5.0.7 on 2025-03-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_formato'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='archivo_rendicion',
            field=models.FileField(blank=True, null=True, upload_to='documentos_rendicion/'),
        ),
        migrations.AddField(
            model_name='documento',
            name='fecha_rendicion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
