# Generated by Django 5.1.3 on 2025-03-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_documento_archivo_rendicion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('FUT', 'FUT'), ('REQ', 'Requerimientos'), ('REQ-PAS', 'Requerimiento-Pasaje'), ('INF', 'Informes')], max_length=10),
        ),
    ]
