# Generated by Django 5.0.7 on 2025-03-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_documento_visado_admin_alter_documento_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='archivo_firmado_gerente',
            field=models.FileField(blank=True, null=True, upload_to='documentos_firmados_gerente/'),
        ),
    ]
