# Generated by Django 5.0.7 on 2025-03-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_documento_archivo_firmado_gerente'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='interno',
            field=models.BooleanField(default=False),
        ),
    ]
